---
new_page_extension: mdx
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: data/blog
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: mdx
- type: heading
  label: Config
- type: document
  path: data/config.json
  label: Site Info
upload_dir: public/static
public_path: public/static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: src/.next
  install_dependencies_command: yarn install
  preview_docker_image: node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
